[package]
name    = "badger-client"
version = "0.1.0"
edition = "2021"

[dependencies]
winit  = "0.26.0"
badger = { path = "../badger" }
glm    = { package = "nalgebra-glm", version = "0.15.0" }

[build-dependencies]
shaderc = "0.7.3"
